trigger:
- main   # change if needed

variables:
  appServiceName: 'yt-clone-web'                  # <-- your App Service name
  acrLoginServer: 'myacr.azurecr.io'              # <-- your ACR login server
  imageName: 'youtube-clone'
  dockerfilePath: 'Dockerfile'
  azureServiceConnection: 'sc-azure-rm'           # <-- your Azure service connection name
  dockerRegistryServiceConnection: 'sc-acr'       # <-- your Docker registry connection name

stages:
- stage: Build_Push
  displayName: Build & Push Docker Image
  jobs:
  - job: Build
    pool:
      name: ''   # <-- your self-hosted agent pool
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build_Push
  jobs:
  - job: DeployJob
    pool:
      name: 'MyLinuxPool'   # <-- self-hosted agent pool
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy container to Web App
      inputs:
        azureSubscription: $(azureServiceConnection)
        appName: $(appServiceName)
        containers: |
          $(acrLoginServer)/$(imageName):$(Build.BuildId)
